[2021-12-13 19:21:42,206] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: postgres_operator_dag.create_pet_table manual__2021-12-13T19:21:41.655886+00:00 [queued]>
[2021-12-13 19:21:42,219] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: postgres_operator_dag.create_pet_table manual__2021-12-13T19:21:41.655886+00:00 [queued]>
[2021-12-13 19:21:42,220] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-13 19:21:42,220] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-12-13 19:21:42,220] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-13 19:21:42,234] {taskinstance.py:1262} INFO - Executing <Task(PostgresOperator): create_pet_table> on 2021-12-13 19:21:41.655886+00:00
[2021-12-13 19:21:42,239] {standard_task_runner.py:52} INFO - Started process 328 to run task
[2021-12-13 19:21:42,243] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'postgres_operator_dag', 'create_pet_table', 'manual__2021-12-13T19:21:41.655886+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/example_postgres.py', '--cfg-path', '/tmp/tmplb1bj7ws', '--error-file', '/tmp/tmpcirydcdq']
[2021-12-13 19:21:42,243] {standard_task_runner.py:77} INFO - Job 4: Subtask create_pet_table
[2021-12-13 19:21:42,288] {logging_mixin.py:109} INFO - Running <TaskInstance: postgres_operator_dag.create_pet_table manual__2021-12-13T19:21:41.655886+00:00 [running]> on host ef07609851a1
[2021-12-13 19:21:42,343] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=postgres_operator_dag
AIRFLOW_CTX_TASK_ID=create_pet_table
AIRFLOW_CTX_EXECUTION_DATE=2021-12-13T19:21:41.655886+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-13T19:21:41.655886+00:00
[2021-12-13 19:21:42,355] {base.py:79} INFO - Using connection to: id: postgres_***_db. Host: postgres-***, Port: 5432, Schema: , Login: ***, Password: ***, extra: {}
[2021-12-13 19:21:42,360] {dbapi.py:225} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS pet (
            pet_id SERIAL PRIMARY KEY,
            name VARCHAR NOT NULL,
            pet_type VARCHAR NOT NULL,
            birth_date DATE NOT NULL,
            OWNER VARCHAR NOT NULL);
          , parameters: None
[2021-12-13 19:21:42,390] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=postgres_operator_dag, task_id=create_pet_table, execution_date=20211213T192141, start_date=20211213T192142, end_date=20211213T192142
[2021-12-13 19:21:42,415] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-13 19:21:42,463] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
