[2021-12-14 08:05:22,629] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: postgres_operator_dag.hook_task manual__2021-12-14T08:05:19.119259+00:00 [queued]>
[2021-12-14 08:05:22,642] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: postgres_operator_dag.hook_task manual__2021-12-14T08:05:19.119259+00:00 [queued]>
[2021-12-14 08:05:22,642] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-14 08:05:22,642] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-12-14 08:05:22,642] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-14 08:05:22,654] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): hook_task> on 2021-12-14 08:05:19.119259+00:00
[2021-12-14 08:05:22,659] {standard_task_runner.py:52} INFO - Started process 795 to run task
[2021-12-14 08:05:22,663] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'postgres_operator_dag', 'hook_task', 'manual__2021-12-14T08:05:19.119259+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/pets_dag.py', '--cfg-path', '/tmp/tmpvv7hd194', '--error-file', '/tmp/tmph_qe2105']
[2021-12-14 08:05:22,663] {standard_task_runner.py:77} INFO - Job 26: Subtask hook_task
[2021-12-14 08:05:22,718] {logging_mixin.py:109} INFO - Running <TaskInstance: postgres_operator_dag.hook_task manual__2021-12-14T08:05:19.119259+00:00 [running]> on host 4ee0ea791fc7
[2021-12-14 08:05:22,771] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=postgres_operator_dag
AIRFLOW_CTX_TASK_ID=hook_task
AIRFLOW_CTX_EXECUTION_DATE=2021-12-14T08:05:19.119259+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-14T08:05:19.119259+00:00
[2021-12-14 08:05:22,781] {base.py:79} INFO - Using connection to: id: ***_conn_id. Host: postgres-***, Port: 5432, Schema: , Login: ***, Password: ***, extra: {}
[2021-12-14 08:05:22,787] {logging_mixin.py:109} INFO - id: 1
[2021-12-14 08:05:22,787] {logging_mixin.py:109} INFO - (1, 'Max', 'Dog', datetime.date(2018, 7, 5), 'Jane')
[2021-12-14 08:05:22,787] {logging_mixin.py:109} INFO - id: 2
[2021-12-14 08:05:22,787] {logging_mixin.py:109} INFO - (2, 'Susie', 'Cat', datetime.date(2019, 5, 1), 'Phil')
[2021-12-14 08:05:22,787] {logging_mixin.py:109} INFO - id: 3
[2021-12-14 08:05:22,787] {logging_mixin.py:109} INFO - (3, 'Lester', 'Hamster', datetime.date(2020, 6, 23), 'Lily')
[2021-12-14 08:05:22,787] {logging_mixin.py:109} INFO - id: 4
[2021-12-14 08:05:22,787] {logging_mixin.py:109} INFO - (4, 'Quincy', 'Parrot', datetime.date(2013, 8, 11), 'Anne')
[2021-12-14 08:05:22,788] {python.py:152} INFO - Done. Returned value was: [(1, 'Max', 'Dog', datetime.date(2018, 7, 5), 'Jane'), (2, 'Susie', 'Cat', datetime.date(2019, 5, 1), 'Phil'), (3, 'Lester', 'Hamster', datetime.date(2020, 6, 23), 'Lily'), (4, 'Quincy', 'Parrot', datetime.date(2013, 8, 11), 'Anne')]
[2021-12-14 08:05:22,813] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=postgres_operator_dag, task_id=hook_task, execution_date=20211214T080519, start_date=20211214T080522, end_date=20211214T080522
[2021-12-14 08:05:22,834] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-14 08:05:22,868] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
